### PR TITLE
Add two scripts for training own dataset.

### PR DESCRIPTION
**Pull request by DayChan**
Add two scripts help to train own dataset.

The `data_to_coco.py` can be used for transferring own data to coco format.

The `edit_model_weight.py` can be used for editing the model weight downloaded from [MODEL_ZOO.md](https://github.com/TuSimple/simpledet/blob/master/MODEL_ZOO.md) for own data training in a simple way.

All the usages have been described in the code.

### CODE REVIEW

**Comment by RogerChern** [comment]
Thanks for your contribution. 
Could you please elaborate the purpose of `edit_model_weight.py` ?
Also, as a reminder, one could just build a roidb for custom data according to [data format](https://github.com/TuSimple/simpledet#preparing-data). No need to first convert it to coco format.

**Comment by DayChan** [comment]
> Thanks for your contribution.
> Could you please elaborate the purpose of `edit_model_weight.py` ?
> Also, as a reminder, one could just build a roidb for custom data according to [data format](https://github.com/TuSimple/simpledet#preparing-data). No need to first convert it to coco format.

The `edit_model_weight.py` is used for converting weight in [MODEL_ZOO.md](https://github.com/TuSimple/simpledet/blob/master/MODEL_ZOO.md) to be suitable for training for different networks (which only changed a little for their datasets).

Though we can directly convert to roidb file, in the test stage, we still need the coco style annotations.

**Comment by RogerChern** [comment]
Would you mind move your files to `utils/contrib` instead of `utils` since these scripts address more specific tasks.

**Comment by DayChan** [comment]
> Would you mind move your files to `utils/contrib` instead of `utils` since these scripts address more specific tasks.

OK, that's fine.

**Pull request merged**
